[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip', 'python39Packages.virtualenv']

[phases.install]
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'gunicorn app:app --bind 0.0.0.0:$PORT'
